# -*- mode: ruby -*-
# vi: set ft=ruby :

# Je définie une variable pour la ram et le cpu
RAM = 2048
CPU = 2
# Je définie une variable pour l'adresse ip privée static
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  # Je configure une adresse ip privé 
  config.vm.network "private_network", ip: IP
  # J'ajoute le provider virtualbox et je lui met l'alias v
  config.vm.provider "virtualbox" do |v|
    # Je configure la ram de la virtualbox
    v.memory = RAM
    # Je configure le CPU de la virtualbox
    v.cpus = CPU
  end # je termine la configuration du virtualbox
end
