# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1048
CPU = 1

Vagrant.configure("2") do |config|

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: "10.0.0.10"
    # le shell va installer nginx et devenir un proxy pour les deux autre serveur
    lb.vm.provision :shell do |shell|
      shell.path = "./shell/lb.sh"
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.network "private_network", ip: "10.0.0.11"
    # J'utilise le shell pour installer nginx et monter un fichier html dans le dossier /var/www/html/index.html 
    # avec un h1 qui attand un argument
    web1.vm.provision :shell do |shell|
      shell.path = "./shell/web.sh"
      # le fichier index.html attant un argument qui s'affichera dans le h1 du fichier
      shell.args = "1"
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.network "private_network", ip: "10.0.0.12"
    # J'utilise le shell pour installer nginx et monter un fichier html dans le dossier /var/www/html/index.html 
    # avec un h1 qui attand un argument
    web2.vm.provision :shell do |shell|
      shell.path = "./shell/web.sh"
      # le fichier index.html attant un argument qui s'affichera dans le h1 du fichier
      shell.args = "2"
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

end

