# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1048
CPU = 1

Vagrant.configure("2") do |config|

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: "10.0.0.10"
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.network "private_network", ip: "10.0.0.11"
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.network "private_network", ip: "10.0.0.12"
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
    end
  end

end
